### PR TITLE
Removed 'PCAWG - Barcelona', 'PCAWG - Heidelberg' and 'PCAWG - Tokyo'

### PR DESCRIPTION
**Pull request by lepsalex**
Repository: stop indexing 'PCAWG - Barcelona', 'PCAWG - Heidelberg' and 'PCAWG - Tokyo' #499

### CODE REVIEW

**Comment by lepsalex** [comment]
ok to test

**Comment by lepsalex** [comment]
add to whitelist

**Comment by lepsalex** [comment]
test this please

**Comment by andricDu** [comment]
add to whitelist

**Review by andricDu — APPROVED** [review]

**Pull request merged**
