### PR TITLE
Index entries in PDC half SONG

### PR DESCRIPTION
**Pull request by blabadi**
issue: https://github.com/icgc-dcc/dcc-portal/issues/553

Additions:
- added songPDCUrl, songPDCToken to application.yml
- added SONGPDCImporter to process song-pdc repository
- added new repository & source for song-pdc
- added new repository collection for song-pdc
- added local run with docker instructions in client module README.md

Modifications:
- added a flag to avoid attempting to translate TCGA barcodes if the repository is song-pdc
- if token is empty skip adding auth header

### CODE REVIEW

**Comment by blabadi** [comment]
add to whitelist

**Comment by blabadi** [comment]
ok to test

**Comment by blabadi** [comment]
this PR pending on input from @junjun-zhang don't merge yet.

**Comment by andricDu** [comment]
add to whitelist

**Comment by andricDu** [comment]
Deployed in prod.

**Pull request merged**
